config/routes.rb
IndividualProject::Application.routes.draw do
  resources :tickets

  resources :people

  root :to => 'tickets#index'

end

app/models/person.rb
class Person < ActiveRecord::Base
  attr_accessible :fname, :lname, :phone
  has_many :tickets

  def name
    fname + " " + lname
  end
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  attr_accessible :cdate, :desc, :person_id, :title
  belongs_to :person
  #acts_as_solr

  def self.searchTickets(query)
    if (query)
      find(:all, :conditions => ['title LIKE ?', "%#{query}%"])
    else
      find(:all)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  # GET /people
  # GET /people.json
  def index
    @people = Person.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @people }
    end
  end

  # GET /people/1
  # GET /people/1.json
  def show
    @person = Person.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @person }
    end
  end

  # GET /people/new
  # GET /people/new.json
  def new
    @person = Person.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @person }
    end
  end

  # GET /people/1/edit
  def edit
    @person = Person.find(params[:id])
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(params[:person])

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render json: @person, status: :created, location: @person }
      else
        format.html { render action: "new" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /people/1
  # PUT /people/1.json
  def update
    @person = Person.find(params[:id])

    respond_to do |format|
      if @person.update_attributes(params[:person])
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person = Person.find(params[:id])
    @person.destroy

    respond_to do |format|
      format.html { redirect_to people_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tickets }
    end
  end

  #Modified
  def index
    @tickets = Ticket.searchTickets(params[:search])
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
    @ticket = Ticket.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ticket }
    end
  end

  # GET /tickets/new
  # GET /tickets/new.json
  def new
    @ticket = Ticket.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ticket }
    end
  end

  # GET /tickets/1/edit
  def edit
    @ticket = Ticket.find(params[:id])
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(params[:ticket])

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render json: @ticket, status: :created, location: @ticket }
      else
        format.html { render action: "new" }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tickets/1
  # PUT /tickets/1.json
  def update
    @ticket = Ticket.find(params[:id])

    respond_to do |format|
      if @ticket.update_attributes(params[:ticket])
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket = Ticket.find(params[:id])
    @ticket.destroy

    respond_to do |format|
      format.html { redirect_to tickets_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IndividualProject</title>
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon bar"></span>
        <span class="icon bar"></span>
        <span class="icon bar"></span>
      </a>
      <a class="brand" href="#"> Help Desk </a>
      <div class="nav-collapse">
       <ul class="nav">
         <li class="active"><%= link_to "Home", tickets_path %></li>
         <li><%= link_to "Customer", people_path %> </li>

       </ul>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="span9"><%= yield %></div>
    <div class="span3">
    </div>
  </div>
</div>

</body>
</html>

app/views/people/_form.html.erb
<%= form_for @person, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :fname, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :fname, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :lname, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :lname, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :phone, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :phone, :class => 'number_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                people_path, :class => 'btn' %>
  </div>
<% end %>

app/views/people/edit.html.erb
<%- model_class = Person -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/people/index.html.erb
<%- model_class = Person -%>
<div class="page-header">
  <h1>Customers</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>

      <th><%= model_class.human_attribute_name(:Name) %></th>

      <th><%= model_class.human_attribute_name(:Phone) %></th>

      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @people.each do |person| %>
      <tr>

        <td><%= link_to person.fname + " " + person.lname, person_path(person) %></td>

        <td><%= person.phone %></td>

        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_person_path(person), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      person_path(person),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_person_path,
            :class => 'btn btn-primary' %>

app/views/people/new.html.erb
<%- model_class = Person -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/people/show.html.erb
<%- model_class = Person -%>
<div class="page-header">
  <h1>Tickets for <%= @person.name %></h1>
</div>

<dl class="dl-horizontal">


  <table>
    <tr>
      <td><b>Date</b></td>
      <td><b>Title</b></td>
      <td><b>Description</b></td>
    </tr>
    <% for ticket in @person.tickets %>
        <tr>
          <td><%= ticket.cdate %></td>
          <td><%= ticket.title %></td>
          <td><%= ticket.desc %></td>
        </tr>
    <% end %>
  </table>

</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              people_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_person_path(@person), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              person_path(@person),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/tickets/_form.html.erb
<%= form_for @ticket, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :cdate, :class => 'control-label' %>
    <div class="controls">
      <%= f.date_select :cdate, :class => 'date_select' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :desc, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :desc, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :Name, :class => 'control-label' %>
    <div class="controls">

      <%= f.select(:person_id, Person.all.collect { |p| [p.name, p.id]}) %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                tickets_path, :class => 'btn' %>
  </div>
<% end %>

app/views/tickets/edit.html.erb
<%- model_class = Ticket -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/tickets/index.html.erb
<%- model_class = Ticket -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>

<h3>Search Tickets by Title</h3>
<%= form_tag tickets_path,:class => "navbar-form pull-left", :method => 'get' do %>
    <%= text_field_tag :search, params[:search],:class => "span2", :placeholder => "search" %>
    <%= submit_tag "Search by Title", :name => nil, :class => 'btn' %>
<%end%>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:Ticket_ID) %></th>
      <th><%= model_class.human_attribute_name(:Creation_Date) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:Description) %></th>
      <th><%= model_class.human_attribute_name(:Customer) %></th>

      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @tickets.each do |ticket| %>
      <tr>
        <td><%= link_to ticket.id, ticket_path(ticket) %></td>
        <td><%= ticket.cdate %></td>
        <td><%= ticket.title %></td>
        <td><%= ticket.desc %></td>
        <td><%= ticket.person.name %></td>

        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_ticket_path(ticket), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      ticket_path(ticket),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_ticket_path,
            :class => 'btn btn-primary' %>

app/views/tickets/new.html.erb
<%- model_class = Ticket -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/tickets/show.html.erb
<%- model_class = Ticket -%>
<div class="page-header">
  <h1>Ticket Details</h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:Creation_Date) %>:</strong></dt>
  <dd><%= @ticket.cdate %></dd>
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @ticket.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:Description) %>:</strong></dt>
  <dd><%= @ticket.desc %></dd>
  <dt><strong><%= model_class.human_attribute_name(:Customer) %>:</strong></dt>
  <dd><%= @ticket.person.name %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              tickets_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_ticket_path(@ticket), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              ticket_path(@ticket),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>